# Generated by Django 2.2.3 on 2019-09-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='points_scored',
            new_name='points',
        ),
    ]
