# Generated by Django 2.2.3 on 2019-09-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190917_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
