# Generated by Django 2.2.3 on 2019-09-18 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190917_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_counter', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='day',
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='main_app.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='day_played',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
    ]
