# Generated by Django 2.2.3 on 2019-09-18 19:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20190918_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_team_ranking', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
                ('rebounds_team_ranking', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
                ('blocks_team_ranking', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
                ('steals_team_ranking', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
                ('turnovers_team_ranking', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
                ('threepointers_team_ranking', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
                ('assists_team_ranking', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
                ('owner_points_team_ranking', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='owner_points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_assists',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_blocks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_rebounds',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_steals',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_threepointers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_turnovers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
