# Generated by Django 2.2.5 on 2019-09-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20190918_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
